\hypertarget{class_array_exception}{}\doxysection{Array\+Exception Class Reference}
\label{class_array_exception}\index{ArrayException@{ArrayException}}


{\ttfamily \#include \char`\"{}Exceptions.\+h\char`\"{}}



Inheritance diagram for Array\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=163pt]{class_array_exception__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for Array\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=163pt]{class_array_exception__coll__graph}
\end{center}
\end{figure}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{class_array_exception_a580e9f660a3293c41154f291369f8c35}{Array\+Exception}} (std\+::string\+\_\+view error)
\item 
const char $\ast$ \mbox{\hyperlink{class_array_exception_a87cd11416e58d1e8398d04937e6a8d9e}{what}} () const noexcept override
\end{DoxyCompactItemize}
\doxysubsection*{Private Attributes}
\begin{DoxyCompactItemize}
\item 
std\+::string \mbox{\hyperlink{class_array_exception_ab0b4567e88f78f313e702eac00ff32fd}{m\+\_\+error}} \{\}
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\hypertarget{class_array_exception_autotoc_md162}{}\doxysubsection{Exceptions}\label{class_array_exception_autotoc_md162}
\mbox{\hyperlink{class_exceptions}{Exceptions}} in C++ are implemented using three keywords that work in conjunction with each other\+:
\begin{DoxyItemize}
\item throw
\item try
\item catch
\end{DoxyItemize}

Exception handling is best used when all of the following are true\+:
\begin{DoxyItemize}
\item the error being handled is likely to occur only infrequently.
\item the error is serious and execution could not continue otherwise.
\item the error cannot be handled at the place where it occurs.
\item there isnâ€™t a good alternative way to return an error code back to the caller.
\end{DoxyItemize}\hypertarget{class_array_exception_autotoc_md163}{}\doxysubsubsection{Throwing exceptions}\label{class_array_exception_autotoc_md163}
A throw statement is used to signal that an exception or error case has occurred, e.\+g.\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\textcolor{keywordflow}{throw} -\/1; \textcolor{comment}{// throw a literal integer value}}
\DoxyCodeLine{\textcolor{keywordflow}{throw} ENUM\_INVALID\_INDEX; \textcolor{comment}{// throw an enum value}}
\DoxyCodeLine{\textcolor{keywordflow}{throw} \textcolor{stringliteral}{"{}Can not take square root of negative number"{}}; \textcolor{comment}{// throw a literal C-\/style (const char*) string}}
\DoxyCodeLine{\textcolor{keywordflow}{throw} dX; \textcolor{comment}{// throw a double variable that was previously defined}}
\DoxyCodeLine{\textcolor{keywordflow}{throw} MyException(\textcolor{stringliteral}{"{}Fatal Error"{}}); \textcolor{comment}{// Throw an object of class MyException}}
\end{DoxyCode}
\hypertarget{class_array_exception_autotoc_md164}{}\doxysubsubsection{Try blocks}\label{class_array_exception_autotoc_md164}
{\bfseries{Try blocks}} act as observers, looking for any exceptions that are thrown within the block, e.\+g.\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\textcolor{keywordflow}{try}}
\DoxyCodeLine{\{}
\DoxyCodeLine{\textcolor{comment}{// Statements that may throw exceptions you want to handle go here}}
\DoxyCodeLine{\textcolor{keywordflow}{throw} -\/1; \textcolor{comment}{// here's a trivial throw statement}}
\DoxyCodeLine{\}}
\end{DoxyCode}
\hypertarget{class_array_exception_autotoc_md165}{}\doxysubsubsection{Handling exceptions}\label{class_array_exception_autotoc_md165}
Actually handling exceptions is the job of the catch block(s). The catch keyword is used to define a block of code (called a catch block) that handles exceptions for a single data type, e.\+g.\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\textcolor{keywordflow}{catch} (\textcolor{keywordtype}{int} x)}
\DoxyCodeLine{\{}
\DoxyCodeLine{\textcolor{comment}{// Handle an exception of type int here}}
\DoxyCodeLine{std::cerr << \textcolor{stringliteral}{"{}We caught an int exception with value"{}} << x << \textcolor{charliteral}{'\(\backslash\)n'};}
\DoxyCodeLine{\}}
\end{DoxyCode}
\hypertarget{class_array_exception_autotoc_md166}{}\doxysubsubsection{Throwing exceptions outside a try-\/block}\label{class_array_exception_autotoc_md166}
...\hypertarget{class_array_exception_autotoc_md167}{}\doxysubsubsection{Catch all handler}\label{class_array_exception_autotoc_md167}
To catch uncaught exceptions, not regarding the type of exception\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\textcolor{keywordflow}{catch} (...) \textcolor{comment}{// catch-\/all handler}}
\DoxyCodeLine{\{}
\DoxyCodeLine{    std::cout << \textcolor{stringliteral}{"{}We caught an exception of an undetermined type\(\backslash\)n"{}};}
\DoxyCodeLine{\}}
\end{DoxyCode}
\hypertarget{class_array_exception_autotoc_md168}{}\doxysubsubsection{Exception classes}\label{class_array_exception_autotoc_md168}
...\hypertarget{class_array_exception_autotoc_md169}{}\doxysubsubsection{std\+::exception}\label{class_array_exception_autotoc_md169}
Many of the classes and operators in the standard library throw exception classes on failure. For example, operator new can throw std\+::bad\+\_\+alloc if it is unable to allocate enough memory. A failed dynamic\+\_\+cast will throw std\+::bad\+\_\+cast. And so on. As of C++17, there are 25 different exception classes that can be thrown, with more being added in each subsequent language standard.

{\bfseries{It is possible to extend std\+::exception, by inheriting.}}\hypertarget{class_array_exception_autotoc_md170}{}\doxysubsubsection{Rethrowing}\label{class_array_exception_autotoc_md170}
When rethrowing the same exception, use the {\itshape throw} keyword by itself.\hypertarget{class_array_exception_autotoc_md171}{}\doxysubsubsection{noexcept}\label{class_array_exception_autotoc_md171}
See \href{https://www.learncpp.com/cpp-tutorial/exception-specifications-and-noexcept/}{\texttt{ exception specifier}}.

It is possible to declare functions non-\/throwing using the {\bfseries{noexcept}} specifier. 

Definition at line \mbox{\hyperlink{_exceptions_8h_source_l00105}{105}} of file \mbox{\hyperlink{_exceptions_8h_source}{Exceptions.\+h}}.



\doxysubsection{Constructor \& Destructor Documentation}
\mbox{\Hypertarget{class_array_exception_a580e9f660a3293c41154f291369f8c35}\label{class_array_exception_a580e9f660a3293c41154f291369f8c35}} 
\index{ArrayException@{ArrayException}!ArrayException@{ArrayException}}
\index{ArrayException@{ArrayException}!ArrayException@{ArrayException}}
\doxysubsubsection{\texorpdfstring{ArrayException()}{ArrayException()}}
{\footnotesize\ttfamily Array\+Exception\+::\+Array\+Exception (\begin{DoxyParamCaption}\item[{std\+::string\+\_\+view}]{error }\end{DoxyParamCaption})}



Definition at line \mbox{\hyperlink{_exceptions_8cpp_source_l00008}{8}} of file \mbox{\hyperlink{_exceptions_8cpp_source}{Exceptions.\+cpp}}.


\begin{DoxyCode}{0}
\DoxyCodeLine{00009         : \mbox{\hyperlink{class_array_exception_ab0b4567e88f78f313e702eac00ff32fd}{m\_error}}\{error\}}
\DoxyCodeLine{00010 \{}
\DoxyCodeLine{00011 \}}

\end{DoxyCode}


\doxysubsection{Member Function Documentation}
\mbox{\Hypertarget{class_array_exception_a87cd11416e58d1e8398d04937e6a8d9e}\label{class_array_exception_a87cd11416e58d1e8398d04937e6a8d9e}} 
\index{ArrayException@{ArrayException}!what@{what}}
\index{what@{what}!ArrayException@{ArrayException}}
\doxysubsubsection{\texorpdfstring{what()}{what()}}
{\footnotesize\ttfamily const char$\ast$ Array\+Exception\+::what (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const\hspace{0.3cm}{\ttfamily [inline]}, {\ttfamily [override]}, {\ttfamily [noexcept]}}



Definition at line \mbox{\hyperlink{_exceptions_8h_source_l00113}{113}} of file \mbox{\hyperlink{_exceptions_8h_source}{Exceptions.\+h}}.


\begin{DoxyCode}{0}
\DoxyCodeLine{00113                                                \{}
\DoxyCodeLine{00114         \textcolor{keywordflow}{return} \mbox{\hyperlink{class_array_exception_ab0b4567e88f78f313e702eac00ff32fd}{m\_error}}.c\_str();}
\DoxyCodeLine{00115     \}}

\end{DoxyCode}


\doxysubsection{Member Data Documentation}
\mbox{\Hypertarget{class_array_exception_ab0b4567e88f78f313e702eac00ff32fd}\label{class_array_exception_ab0b4567e88f78f313e702eac00ff32fd}} 
\index{ArrayException@{ArrayException}!m\_error@{m\_error}}
\index{m\_error@{m\_error}!ArrayException@{ArrayException}}
\doxysubsubsection{\texorpdfstring{m\_error}{m\_error}}
{\footnotesize\ttfamily std\+::string Array\+Exception\+::m\+\_\+error \{\}\hspace{0.3cm}{\ttfamily [private]}}



Definition at line \mbox{\hyperlink{_exceptions_8h_source_l00108}{108}} of file \mbox{\hyperlink{_exceptions_8h_source}{Exceptions.\+h}}.



The documentation for this class was generated from the following files\+:\begin{DoxyCompactItemize}
\item 
learning\+Cpp/\+Errors/\mbox{\hyperlink{_exceptions_8h}{Exceptions.\+h}}\item 
learning\+Cpp/\+Errors/\mbox{\hyperlink{_exceptions_8cpp}{Exceptions.\+cpp}}\end{DoxyCompactItemize}
