<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=9"/>
	<meta name="generator" content="Doxygen 1.8.20"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<title>Cpp concept project: learningCpp/Errors/TestingExceptions.cpp File Reference</title>
	<link href="tabs.css" rel="stylesheet" type="text/css"/>
	<script type="text/javascript" src="jquery.js"></script>
	<script type="text/javascript" src="dynsections.js"></script>
	<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
	<link href="doxygen-custom.css" rel="stylesheet" type="text/css" />
	<!-- Add icon library -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Add font awesome icons -->
</head>
<body>
	<div id="banner">
		<div class="logo">
			<span class="subtitle">
				API Documentation for C++ template project
			</span>
			<!-- <span class="search">
				<input type="text" placeholder="Search" onkeydown="search(this,event);">
			</span> -->
		</div>
	<div class="icon-bar">
		<a href="https://de-de.facebook.com/" class="fa fa-facebook"></a>
		<a href="https://twitter.com/?lang=de" class="fa fa-twitter"></a>
		<a href="https://github.com/" class="fa fa-github"></a>
		<a href="https://www.youtube.com/?gl=DE&hl=de" class="fa fa-youtube"></a>
		<a href="https://www.linkedin.com/login/de" class="fa fa-linkedin"></a>
		<a href="https://about.gitlab.com/?utm_medium=cpc&utm_source=google&utm_campaign=brand_emea_pr_rsa_br_exact&utm_content=homepage_digital_x-pr_english_&_bt=363211725518&_bk=gitlab&_bm=e&_bn=g&_bg=75294586319&gclid=EAIaIQobChMI1rKi_ICR7QIVV53VCh2igg88EAAYASAAEgKcFPD_BwE" class="fa fa-gitlab"></a>
		<a href="https://uni-tuebingen.de/" class="fa fa-university"></a>
		<a href="https://slack.com/intl/de-de/" class="fa fa-slack"></a>
		<a href="#" class="fa fa-share-alt"></a>
		<a href="https://de.wikipedia.org/wiki/Wikipedia:Hauptseite" class="fa fa-wikipedia-w"></a>
	</div>
	</div>
	<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<!-- Generated by Doxygen 1.8.20 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_94b3207fdcdf159a761ccdefa33582c9.html">learningCpp</a></li><li class="navelem"><a class="el" href="dir_d0cf561f68ff83abbf77f715893f8c17.html">Errors</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">TestingExceptions.cpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="_exceptions_8h_source.html">Exceptions.h</a>&quot;</code><br />
<code>#include &lt;iostream&gt;</code><br />
<code>#include &lt;string&gt;</code><br />
<code>#include &lt;exception&gt;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for TestingExceptions.cpp:</div>
<div class="dyncontent">
<div class="center"><img src="_testing_exceptions_8cpp__incl.png" border="0" usemap="#alearning_cpp_2_errors_2_testing_exceptions_8cpp" alt=""/></div>
<map name="learning_cpp_2_errors_2_testing_exceptions_8cpp" id="alearning_cpp_2_errors_2_testing_exceptions_8cpp">
<area shape="rect" title=" " alt="" coords="213,5,372,47"/>
<area shape="rect" href="_exceptions_8h.html" title=" " alt="" coords="201,95,299,121"/>
<area shape="rect" title=" " alt="" coords="5,169,84,196"/>
<area shape="rect" title=" " alt="" coords="303,169,375,196"/>
<area shape="rect" title=" " alt="" coords="400,169,455,196"/>
<area shape="rect" title=" " alt="" coords="221,169,279,196"/>
<area shape="rect" title=" " alt="" coords="109,169,197,196"/>
</map>
</div>
</div>
<p><a href="_testing_exceptions_8cpp_source.html">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ae66f6b31b5ad750f1fe042a706a4e3d4"><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="_testing_exceptions_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4">main</a> ()</td></tr>
<tr class="separator:ae66f6b31b5ad750f1fe042a706a4e3d4"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a id="ae66f6b31b5ad750f1fe042a706a4e3d4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae66f6b31b5ad750f1fe042a706a4e3d4">&#9670;&nbsp;</a></span>main()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int main </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="_testing_exceptions_8cpp_source.html#l00011">11</a> of file <a class="el" href="_testing_exceptions_8cpp_source.html">TestingExceptions.cpp</a>.</p>
<div class="fragment"><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;           {</div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160; </div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;    <span class="keywordflow">try</span></div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;    {</div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;        <span class="comment">// Statements that may throw exceptions you want to handle go here</span></div>
<div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;        <span class="keywordflow">throw</span> -1; <span class="comment">// here&#39;s a trivial example</span></div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;    }</div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keywordflow">catch</span> (<span class="keywordtype">int</span> x)</div>
<div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    {</div>
<div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;        <span class="comment">// Any exceptions of type int thrown within the above try block get sent here</span></div>
<div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;We caught an int exception with value: &quot;</span> &lt;&lt; x &lt;&lt; <span class="charliteral">&#39;\n&#39;</span>;</div>
<div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    }</div>
<div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;    <span class="keywordflow">catch</span> (<span class="keywordtype">double</span>) <span class="comment">// no variable name since we don&#39;t use the exception itself in the catch block below</span></div>
<div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;    {</div>
<div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;        <span class="comment">// Any exceptions of type double thrown within the above try block get sent here</span></div>
<div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;We caught an exception of type double&quot;</span> &lt;&lt; <span class="charliteral">&#39;\n&#39;</span>;</div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;    }</div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;    <span class="keywordflow">catch</span> (<span class="keyword">const</span> std::string &amp;str) <span class="comment">// catch classes by const reference</span></div>
<div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;    {</div>
<div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        <span class="comment">// Any exceptions of type std::string thrown within the above try block get sent here</span></div>
<div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;We caught an exception of type std::string&quot;</span> &lt;&lt; <span class="charliteral">&#39;\n&#39;</span>;</div>
<div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;    }</div>
<div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160; </div>
<div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;    std::cout &lt;&lt; <span class="stringliteral">&quot;Continuing on our merry way\n&quot;</span>;</div>
<div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160; </div>
<div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160; </div>
<div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;    <span class="keywordtype">double</span> x{ -1 };</div>
<div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160; </div>
<div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;    <span class="keywordflow">try</span> <span class="comment">// Look for exceptions that occur within try block and route to attached catch block(s)</span></div>
<div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;    {</div>
<div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;        <span class="keywordtype">double</span> d = <a class="code" href="class_s_q_r_t.html#ad38eaa006bce8d7bfc20c54ce915af60">SQRT::mySqrt</a>(x);</div>
<div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;        std::cout &lt;&lt; <span class="stringliteral">&quot;The sqrt of &quot;</span> &lt;&lt; x &lt;&lt; <span class="stringliteral">&quot; is &quot;</span> &lt;&lt; d &lt;&lt; <span class="charliteral">&#39;\n&#39;</span>;</div>
<div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    }</div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;    <span class="keywordflow">catch</span> (<span class="keyword">const</span> <span class="keywordtype">char</span>* exception) <span class="comment">// catch exceptions of type const char*</span></div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    {</div>
<div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;Error: &quot;</span> &lt;&lt; exception &lt;&lt; std::endl;</div>
<div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;    }</div>
<div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160; </div>
<div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;    <span class="keywordflow">try</span></div>
<div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;    {</div>
<div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        <span class="comment">// Your code using standard library goes here</span></div>
<div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        <span class="comment">// We&#39;ll trigger one of these exceptions intentionally for the sake of example</span></div>
<div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;        std::string s;</div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        s.resize(-1); <span class="comment">// will trigger a std::length_error</span></div>
<div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;    }</div>
<div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        <span class="comment">// This handler will catch std::exception and all the derived exceptions too</span></div>
<div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;    <span class="keywordflow">catch</span> (<span class="keyword">const</span> std::exception &amp;exception)</div>
<div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;    {</div>
<div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;Standard exception: &quot;</span> &lt;&lt; exception.what() &lt;&lt; <span class="charliteral">&#39;\n&#39;</span>;</div>
<div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;    }</div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160; </div>
<div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;    <span class="keywordflow">try</span></div>
<div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;    {</div>
<div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        <span class="keywordflow">throw</span> std::runtime_error(<span class="stringliteral">&quot;Bad things happened&quot;</span>);</div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;    }</div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;        <span class="comment">// This handler will catch std::exception and all the derived exceptions too</span></div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;    <span class="keywordflow">catch</span> (<span class="keyword">const</span> std::exception &amp;exception)</div>
<div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;    {</div>
<div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;Standard exception: &quot;</span> &lt;&lt; exception.what() &lt;&lt; <span class="charliteral">&#39;\n&#39;</span>;</div>
<div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;    }</div>
<div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160; </div>
<div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;    <a class="code" href="class_int_array.html">IntArray</a> array;</div>
<div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160; </div>
<div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;    <span class="keywordflow">try</span></div>
<div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;    {</div>
<div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;        <span class="keywordtype">int</span> value{ array[5] };</div>
<div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;    }</div>
<div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;    <span class="keywordflow">catch</span> (<span class="keyword">const</span> <a class="code" href="class_array_exception.html">ArrayException</a> &amp;exception) <span class="comment">// derived catch blocks go first</span></div>
<div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;    {</div>
<div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;An array exception occurred (&quot;</span> &lt;&lt; exception.<a class="code" href="class_array_exception.html#a87cd11416e58d1e8398d04937e6a8d9e">what</a>() &lt;&lt; <span class="stringliteral">&quot;)\n&quot;</span>;</div>
<div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;    }</div>
<div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;    <span class="keywordflow">catch</span> (<span class="keyword">const</span> std::exception &amp;exception)</div>
<div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;    {</div>
<div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        std::cerr &lt;&lt; <span class="stringliteral">&quot;Some other std::exception occurred (&quot;</span> &lt;&lt; exception.what() &lt;&lt; <span class="stringliteral">&quot;)\n&quot;</span>;</div>
<div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;    }</div>
<div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160; </div>
<div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;    <span class="keywordflow">return</span> 0;</div>
<div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;}</div>
</div><!-- fragment --><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="_testing_exceptions_8cpp_ae66f6b31b5ad750f1fe042a706a4e3d4_cgraph.png" border="0" usemap="#a_testing_exceptions_8cpp_ae66f6b31b5ad750f1fe042a706a4e3d4_cgraph" alt=""/></div>
<map name="_testing_exceptions_8cpp_ae66f6b31b5ad750f1fe042a706a4e3d4_cgraph" id="a_testing_exceptions_8cpp_ae66f6b31b5ad750f1fe042a706a4e3d4_cgraph">
<area shape="rect" title=" " alt="" coords="5,31,56,57"/>
<area shape="rect" href="class_s_q_r_t.html#ad38eaa006bce8d7bfc20c54ce915af60" title=" " alt="" coords="124,5,231,32"/>
<area shape="rect" href="class_array_exception.html#a87cd11416e58d1e8398d04937e6a8d9e" title=" " alt="" coords="104,56,251,83"/>
</map>
</div>

</div>
</div>
</div><!-- contents -->
<div class="ttc" id="aclass_int_array_html"><div class="ttname"><a href="class_int_array.html">IntArray</a></div><div class="ttdef"><b>Definition:</b> <a href="_exceptions_8h_source.html#l00118">Exceptions.h:119</a></div></div>
<div class="ttc" id="aclass_array_exception_html"><div class="ttname"><a href="class_array_exception.html">ArrayException</a></div><div class="ttdef"><b>Definition:</b> <a href="_exceptions_8h_source.html#l00105">Exceptions.h:106</a></div></div>
<div class="ttc" id="aclass_s_q_r_t_html_ad38eaa006bce8d7bfc20c54ce915af60"><div class="ttname"><a href="class_s_q_r_t.html#ad38eaa006bce8d7bfc20c54ce915af60">SQRT::mySqrt</a></div><div class="ttdeci">static double mySqrt(double x)</div><div class="ttdef"><b>Definition:</b> <a href="_exceptions_8cpp_source.html#l00028">Exceptions.cpp:28</a></div></div>
<div class="ttc" id="aclass_array_exception_html_a87cd11416e58d1e8398d04937e6a8d9e"><div class="ttname"><a href="class_array_exception.html#a87cd11416e58d1e8398d04937e6a8d9e">ArrayException::what</a></div><div class="ttdeci">const char * what() const noexcept override</div><div class="ttdef"><b>Definition:</b> <a href="_exceptions_8h_source.html#l00113">Exceptions.h:113</a></div></div>
<!-- start footer part -->
  <hr class="footer"/><address class="footer"><small>
    Cpp concept project  - learningCpp/Errors/TestingExceptions.cpp File Reference<br />
    Generated on Fri Dec 11 2020 12:03:32 by <a href="http://www.doxygen.org/index.html">Doxygen</a> 1.8.20
  </small></address>
</body>
</html>